# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Release for tag

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history.
          # all history for changelog
          fetch-depth: 0

      - name: Setup node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://registry.npmjs.org

      - name: Environment variables
        run: |
          env

      - name: Install
        run: |
          npm ci
          npm run bootstrap

      - name: ESLint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Publish to npm
        # https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
        id: publish-to-npm
        env:
          # need set in GitHub repo - settings - secrets
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat ./.npmrc
          npm publish
